version: '2'
services:
  gogs:
    image: gogs/gogs 
    container_name: ${PROJECT_NAME}-${DEV_USER}-gogs
    volumes:
      - ../database/gogs:/data
    ports:
      # - "-:22"
      - "${GOGS_PORT}:3000"
    networks:
      - default
networks:
  default:
    external:
      name: ${DEV_USER}
