version: '2'
services:
  rancher:
    image: rancher/rancher
    container_name: ${PROJECT_NAME}-${DEV_USER}-rancher
    volumes:
      - ../etcd:/var/lib/rancher/etcd
    ports:
      - "${RANCHER_PORT}:80"
      - "${RANCHER_SSL_PORT}:443"
    networks:
      - default
networks:
  default:
    external:
      name: ${DEV_USER}
