version: '2'
services:
  front-envoy:
    image: ${REGISTRY_PREFIX}:envoy
    container_name: ${PROJECT_NAME}-${DEV_USER}-envoy
    volumes:
      - ../config/envoy.yaml:/etc/front-envoy.yaml
    ports:
      - "${ENVOY_PORT}:80"
      - "${ENVOY_ADMIN_PORT}:8001"
    networks:
      - default
networks:
  default:
    external:
      name: ${DEV_USER}
