apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-local-pv
  # annotations:
  #   "volume.alpha.kubernetes.io/node-affinity": '{
  #     "requiredDuringSchedulingIgnoredDuringExecution": {
  #       "nodeSelectorTerms": [
  #         { "matchExpressions": [
  #           { "key": "kubernetes.io/hostname",
  #             "operator": "In",
  #             "values": ["my-node"]
  #           }
  #         ]}
  #        ]}
  #       }',
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-mysql
  local:
    path: /home/wuzhongyang/database/mysql

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-local-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-mysql
